from youtube_search import YoutubeSearch
from thefuzz import fuzz
# import webbrowser
import json
import time
import pandas as pd
import requests
# from pynput.keyboard import Key, Controller

raga_list = [
    "Aadi Basant",
    "Aadi",
    "Aarabi",
    "Abheri Todi",
    "Abheri",
    "Abhogi Kanada",
    "Abhogi",
    "Achob",
    "Adambari Kedar",
    "Adana Bahar",
    "Adana Malhar",
    "Adana",
    "Adbhut Kalyan",
    "Adbhut Ranjani",
    "Aghali",
    "Ahimohini",
    "Ahir Bhairav",
    "Ahir Kanada",
    "Ahir Lalat",
    "Ahir Lalit",
    "Ahiri Malhar",
    "Ahiri Todi",
    "Ahiri",
    "Ajad Hindol",
    "Ajad",
    "Alamgiri",
    "Alhaiya Bilaval",
    "Alhaiya",
    "Amari",
    "Amba Manohari",
    "Ambika Sarang",
    "Amiri Kauns",
    "Amrith Kalyan",
    "Amritvarshini",
    "Ananda Bhairav",
    "Ananda Leela",
    "Ananda Malhar",
    "Ananda",
    "Anandi Bahar",
    "Anandi Kalyan",
    "Anandi Kedar",
    "Anandi kedar",
    "Anandi",
    "Andhri",
    "Andiyali",
    "Anjani Kalyan",
    "Anjani Todi",
    "Anuranjani",
    "Araj",
    "Arjun",
    "Arun Malhar",
    "Asa Asavari",
    "Asa Bhairav",
    "Asa Kafi",
    "Asa Maand",
    "Asa Mand",
    "Asa Todi",
    "Asa",
    "Asavari Todi",
    "Asavari",
    "Aslekhi",
    "Audav Bhairav",
    "Audav Bilawal",
    "Audav Devgiri",
    "Audav Dhannasri",
    "Audav Gandhar",
    "Audav Girija",
    "Audav Kauns",
    "Audav Shuddha Kalyan",
    "Audav",
    "Averi Bhairavi",
    "Badhamsa Sarang",
    "Badhans",
    "Bageshree Bahar",
    "Bageshree Kanada",
    "Bageshree Kauns",
    "Bageshree",
    "Bageshri Bahar",
    "Bageshri Kanada",
    "Bageshri Kauns",
    "Bagkauns",
    "Bahaduri Todi",
    "Bahar",
    "Bahari Kedar",
    "Bairagi Bhairav",
    "Bairagi Todi",
    "Bairagi",
    "Bajra",
    "Bakul Bhairav",
    "Bakulabharan",
    "Ban",
    "Bangal Bhairav",
    "Bangal Bilawal",
    "Bangal",
    "Bangli",
    "Banjara",
    "Barahansika",
    "Barari",
    "Barathi Todi",
    "Barati",
    "Barhams Sarang",
    "Barwa",
    "Basant Bahar",
    "Basant Hindol",
    "Basant Kedar",
    "Basant Mukhari",
    "Basant Pancham",
    "Basant",
    "Basanta Mukhari",
    "Basanti Kanada",
    "Basanti Kauns",
    "Basanti Kedar",
    "Basanti",
    "Bayati",
    "Beehad Bhairav",
    "Beehad",
    "Bhadrakauns",
    "Bhagabati",
    "Bhairav Bahar",
    "Bhairav Bhatiyar",
    "Bhairav",
    "Bhairavi",
    "Bhankhar",
    "Bhankhari",
    "Bhaskali",
    "Bhasker",
    "Bhatiyar",
    "Bhatiyari Bhairav",
    "Bhatiyari Gauri",
    "Bhatiyari",
    "Bhav Kauns",
    "Bhavana pancham",
    "Bhavmat Bhairav",
    "Bhavmat",
    "Bhavsakh Kanada",
    "Bhavsakh",
    "Bhawani Bahar",
    "Bhawani Bhairav",
    "Bhawani",
    "Bhilalu",
    "Bhim",
    "Bhimpalasi",
    "Bhimsen",
    "Bhinna Bhairav",
    "Bhinna Kauns",
    "Bhinna Lalat",
    "Bhinna Rageshri",
    "Bhinna Shadja",
    "Bhookosh",
    "Bhoopal Todi",
    "Bhoopal",
    "Bhoopali",
    "Bhoopeshwari",
    "Bhora",
    "Bhup Bilawal",
    "Bhup Kalyan",
    "Bhup Nat",
    "Bhupal Todi",
    "Bhupali",
    "Bhupawali",
    "Bhupkali",
    "Bhuplai",
    "Bhuvaneshvari",
    "Bibhas Parbhati",
    "Bibhas",
    "Bihag Maalva",
    "Bihag Nat",
    "Bihag Pat",
    "Bihag Savani",
    "Bihag",
    "Bihagada",
    "Bihagda",
    "Bihagora Maalva",
    "Bihagora",
    "Bihari Todi",
    "Bihari",
    "Bilahari",
    "Bilaskhani Todi",
    "Bilawal Dakhani",
    "Bilawal Gond",
    "Bilawal Kukubh",
    "Bilawal Malhar",
    "Bilawal Nat",
    "Bilawal Shukla",
    "Bilawal",
    "Bilawali",
    "Binoda",
    "Biradhar",
    "Birju ki Malhar",
    "Brindabani Sarang",
    "Chaiti Barwa",
    "Chaiti Bhup",
    "Chaiti",
    "Chakradhar",
    "Chakravaak",
    "Chalnat",
    "Champak Bilawal",
    "Champak",
    "Champakali",
    "Chanchalsas Malhar",
    "Chand",
    "Chandani Bihag",
    "Chandani Kalyan",
    "Chandani Kedar",
    "Chandani Todi",
    "Chandani",
    "Chandika",
    "Chandra Bhairav",
    "Chandra Bhankar",
    "Chandra Kalyan",
    "Chandrabimb",
    "Chandradhwani",
    "Chandrakant",
    "Chandrakauns",
    "Chandramouli",
    "Chandranandan",
    "Chandraprabha",
    "Chandrika",
    "Charju ki Malhar",
    "Charjuki Malhar",
    "Charu Kauns",
    "Charukauns",
    "Charukeshi",
    "Chaya",
    "Chhaya bihag",
    "Chhaya Gaud Sarang",
    "Chhaya Hindol",
    "Chhaya Kalyan",
    "Chhaya Malhar",
    "Chhaya Tilak",
    "Chhaya",
    "Chhayanat",
    "Dadori",
    "Dagori",
    "Dakshina Gujjari",
    "Dakshinatya",
    "Daras Kauns",
    "Darbari Kanada",
    "Darbari Todi",
    "Darbari",
    "Daulati",
    "Dayabati",
    "Debsaakh Kanada",
    "Deepak Kedar",
    "Deepak",
    "Deepawali",
    "Deepranjani",
    "Deogandhara",
    "Deosakh",
    "Desaa Jaldhar",
    "Desaa Sawan",
    "Desaa Sorath",
    "Desh Gaud",
    "Desh Jogi",
    "Desh Malhar",
    "Desh",
    "Deshakhya",
    "Deshi Tilang",
    "Deshi",
    "Deshkar",
    "Desi Devgiri",
    "Desi Todi",
    "Dev Gandhar",
    "Dev Todi",
    "Devadarshini",
    "Devangi",
    "Devaranjani",
    "Devata Bhairav",
    "Devgaandhari",
    "Devgiri Bilawal",
    "Devgiri",
    "Devkari",
    "Devkauns",
    "Devmaya",
    "Devsag",
    "Devtirthi",
    "Dhabalashri",
    "Dhakka",
    "Dhan Basanti",
    "Dhanakoni Kalyan",
    "Dhanashri Multani",
    "Dhanashri",
    "Dhanawarchi Kalyan",
    "Dhani",
    "Dhanikauns",
    "Dhanki",
    "Dhankosh",
    "Dhanya Dhaivat",
    "Dharmavati",
    "Dhavalshree",
    "Dhulia Malhar",
    "Dhulia Sarang",
    "Dhumavati",
    "Din Ka Malkauns",
    "Din ka Shankara",
    "Din ki Puriya",
    "Dipika",
    "Dishakh",
    "Divyagandhar",
    "Diwali",
    "Doga Kalyan",
    "Dravida Gauda",
    "Dravida Gujjari",
    "Durga Kalyan",
    "Durga Kedar",
    "Durga",
    "Durgawati",
    "Durgeshvari",
    "Durgeshwari",
    "Dwijavanthi",
    "Enayatkhani Kanada",
    "Erukalakambhoji",
    "Gagan Vihang",
    "Gajdhar",
    "Gambhir",
    "Gandhakriya",
    "Gandhara",
    "Gandhari Bahar",
    "Gandhari",
    "Gandhi Bilawal",
    "Gandhi Malhar",
    "Gandhi",
    "Ganeshwari",
    "Gangeshwari",
    "Gara Bageshri",
    "Gara Kanada",
    "Gara Mand",
    "Gara",
    "Gaud Bahar",
    "Gaud Bilawal",
    "Gaud Malhar",
    "Gaud Sarang",
    "Gaud",
    "Gaudgiri Bahar",
    "Gaudi Bahar",
    "Gaudi Lalat",
    "Gaudi Malari",
    "Gaudi",
    "Gaul",
    "Gaundkari",
    "Gauri Bairagan",
    "Gauri Basant",
    "Gauri Chayti",
    "Gauri Cheti",
    "Gauri Dakhani",
    "Gauri Deepaki",
    "Gauri Guarairi",
    "Gauri Lalita",
    "Gauri Majh",
    "Gauri Mala",
    "Gauri Malva",
    "Gauri Purbi Deepaki",
    "Gauri Purbi",
    "Gauri Sorath",
    "Gauri",
    "Gawati",
    "Girija Audav",
    "Girija Bhairav",
    "Girija Gandhar",
    "Girija Kauns",
    "Godagir",
    "Gop Kamboji",
    "Gopika Basant",
    "Gopika",
    "Gorakh Kalyan",
    "Gound",
    "Govardhani Todi",
    "Gujjari",
    "Guna Kalyan",
    "Guna Sagra",
    "Gunakali Jogia",
    "Gunakali Utari",
    "Gunakali",
    "Gunakree",
    "Gunaranjani",
    "Gund",
    "Gunguni",
    "Gunji Kanada",
    "Gunji Kanhara",
    "Gunjikauns",
    "Gunkali",
    "Gunkiri",
    "Gurjari Todi",
    "Gurjari",
    "Gurjri",
    "Guru Kalyan",
    "Gyankali",
    "Haimanti",
    "Hameer Bahar",
    "Hameer Bilawal",
    "Hameer Kalyan",
    "Hameer Kedar",
    "Hameer Tarang",
    "Hameer",
    "Hameeri Bilawal",
    "Hameeri",
    "Hamsa Kalyan",
    "Hamsadhvani",
    "Hamsadhwani",
    "Hamviri",
    "Hansakinkini",
    "Hansanarayani",
    "Hanskinkini",
    "Hansvinod",
    "Harakh",
    "Harasringara",
    "Hari Kauns",
    "Hari Priya",
    "Harsha",
    "Harshsrungara",
    "Hasantrehta",
    "Haunsnad",
    "Hem Behag",
    "Hem Bihag",
    "Hem Kalyan",
    "Hem Lalat",
    "Hem Nat",
    "Hem",
    "Hemant Bhairav",
    "Hemant",
    "Hemshri",
    "Hemvanti",
    "Hemvati",
    "Hijaj Bhairav",
    "Hijaj",
    "Himala",
    "Hindol Ajad",
    "Hindol Bahar",
    "Hindol Basant",
    "Hindol Hem",
    "Hindol Kalyan",
    "Hindol Marg",
    "Hindol Pancham",
    "Hindol",
    "Hindoli",
    "Hindolita",
    "Homshikha",
    "Hussaini Bhairavi",
    "Hussaini Kanada",
    "Hussaini Todi",
    "Hussani Todi",
    "Iman",
    "Imni Manjh",
    "Imratkauns",
    "Inayatkhani Kanada",
    "Indrasan",
    "Indumati",
    "Jablidhar",
    "Jaij Bilawal",
    "Jaijaiwanti Kanada",
    "Jaijaiwanti Todi",
    "Jaijaiwanti",
    "JaiKauns",
    "Jaimini Kalyan",
    "Jaimini",
    "JaiRaj",
    "Jait Kalyan",
    "Jait",
    "Jaitshri",
    "Jaiwanti",
    "Jaladhar Basanti",
    "Jaladhar Desa",
    "Jaladhar Kedar",
    "Jaldhara",
    "Janasammohini",
    "Janasanmodini",
    "Jangla Purvi",
    "Jangula",
    "Jaun",
    "Jaunkali",
    "Jaunpuri Bahar",
    "Jaunpuri Todi",
    "Jaunpuri",
    "Jaya",
    "Jayant Kanada",
    "Jayant Malhar",
    "Jayant",
    "Jayanti",
    "Jayat Kalyan",
    "Jayet",
    "Jetashree",
    "Jhanjh Malhar",
    "Jhilla",
    "Jhinjhoti Misravanti",
    "Jhinjhoti",
    "Jog Bahar",
    "Jog Tilang",
    "Jog",
    "Jogeshwari",
    "Jogi Bhairavi",
    "Jogi Mand",
    "Jogi",
    "Jogia Kalingada",
    "Jogia",
    "Jogiya Asavari",
    "Jogiya",
    "Jogkauns",
    "Jogwanti",
    "Joun Bhairav",
    "Jungala",
    "Kaalanka",
    "Kaamaai",
    "Kaamkesh",
    "Kaanara",
    "Kabir Bhairav",
    "Kabiri Gauri",
    "Kabiri",
    "Kachheli",
    "Kafi Bahar",
    "Kafi Kanada",
    "Kafi Malhar",
    "Kafi",
    "Kagnat",
    "Kaisiki",
    "Kakambheri",
    "Kakubha",
    "Kala Bharan",
    "Kalahans",
    "Kalaranjani",
    "Kalashree",
    "Kalian Bhopali",
    "Kalian",
    "Kalinga",
    "Kalingada",
    "Kalingda",
    "Kalyan",
    "Kalyani",
    "Kamakshani",
    "Kamal Shree",
    "Kamal",
    "Kamalaranjani",
    "Kamboji",
    "Kameshwari",
    "Kamkesh",
    "Kamod Nat",
    "Kamod",
    "Kamodi",
    "Kamodwanti",
    "Kampili",
    "Kanada Bageshri",
    "Kanada Bahar",
    "Kanada",
    "Kanakanagi",
    "Kanaraya",
    "Kanmala",
    "Kannadi",
    "Kanra",
    "Kapar Gauri",
    "Kapi",
    "Karnataka Bangala",
    "Karnataki",
    "Karnati",
    "Kaunsi",
    "Kaushi Kanada",
    "Kaushik Kanada",
    "Kaushik Todi",
    "Kaushik",
    "Kaushikdwani",
    "Kaushiki",
    "Kausi",
    "Kedar Bahar",
    "Kedar Bhairav",
    "Kedar Bhankar",
    "Kedar Mand",
    "Kedar Manjh",
    "Kedar Nand",
    "Kedar Nat",
    "Kedar",
    "Kedari Malhar",
    "Kedari",
    "KedarNanda",
    "Keki",
    "Kesari Kalyan",
    "Khamaj Bahar",
    "Khamaj",
    "Khambabati",
    "Khambavati",
    "Khammaji Bhatiyar",
    "Khapar Gauri",
    "Khat Dhanashree",
    "Khat Todi",
    "Khat",
    "Khem Kalyan",
    "Khem",
    "Khemb",
    "Khemdhwan",
    "Khemnat",
    "Khokar",
    "Khokat",
    "Kiranranjani",
    "Kiwani",
    "Klawanti",
    "Kohal",
    "Kohari Kalyan",
    "Kokabh",
    "Kokar",
    "Kokila Pancham",
    "Kola",
    "Kolahal",
    "Kolhaas",
    "Komal Bageshri",
    "Komal Bhairav",
    "Komal Bhimpalasi",
    "Komal Desi",
    "Komal Marwa",
    "Komal Rishabh Asavari",
    "Koumari",
    "Kripavati",
    "Krishna Kalyan",
    "Krulanda",
    "Kukubh Bilawal",
    "Kukubh",
    "Kumbh",
    "Kumbhara",
    "Kumodini",
    "Kunada",
    "Kuntal",
    "Kuranji",
    "Kusha",
    "Kusum",
    "Lacchasakh",
    "Lachari Kanada",
    "Lachari Todi",
    "Lachchasakh",
    "Lachhasas",
    "Lagan Gandhar",
    "Lajwanti",
    "Lakshmi Kalyan",
    "Lakshmi Todi",
    "Lalat Bahar",
    "Lalat Pancham",
    "Lalat",
    "Lalit Bhatiyar",
    "Lalit Bilas",
    "Lalit Pancham",
    "Lalit",
    "Lalita Gauri",
    "Lalita Sohani",
    "Lalita Sohini",
    "Lalita",
    "Lalitdhwani",
    "Lalitkali",
    "Lankadahan Sarang",
    "Lankeshri Kanada",
    "Lankeshri",
    "Lankeshwari",
    "Lataangi",
    "Lom",
    "Maalva",
    "Madanmanjari",
    "Madha Kalyan",
    "Madhabsri",
    "Madhakauns",
    "Madhasuraja",
    "Madhava",
    "Madhavgiri",
    "Madhu Basant",
    "Madhu Kalyan",
    "Madhu Malhar",
    "Madhu Malvi",
    "Madhu Sarang",
    "Madhu Saraswati",
    "Madhu",
    "Madhukali",
    "Madhukauns",
    "Madhumad Sarang",
    "Madhumadh Sarang",
    "Madhumadhavi",
    "Madhumalati",
    "Madhuranjani",
    "Madhusurawali",
    "Madhuwanti",
    "Madhyamad Sarang",
    "Madhyamavati",
    "Maharashtra Gujjari",
    "Mahathi",
    "Majh",
    "Malani",
    "Malashree",
    "Malati Basant",
    "Malati Bihag",
    "Malati",
    "Malava",
    "Malavasri",
    "Malavi",
    "Malawa Bihag",
    "Malawati",
    "Malaya",
    "Malayalam",
    "Malgunj",
    "Malgunji",
    "Malhar",
    "Malhari",
    "Mali Gaura",
    "Maligaura",
    "Malini Basant",
    "Malkauns Bahar",
    "Malkauns Kanada",
    "Malkauns Pancham",
    "Malkauns",
    "Mallari",
    "Maluha Bihag",
    "Maluha Kalyan",
    "Maluha Kedar",
    "Maluha Mand",
    "Maluha",
    "Manamanjari",
    "Manavi",
    "Mand Bhairav",
    "Mand Bhatiyar",
    "Mand",
    "Mangal Bhairav",
    "Mangal Lalit",
    "Mangal Todi",
    "Mangalan",
    "Mangaldhwani",
    "Mangalgujari",
    "Mangiya Bhusani",
    "Manj Khamaj",
    "Manjari Bihag",
    "Manjari",
    "Manjh Khamaj",
    "Manjha Khamaj",
    "Manjubhashini",
    "Marg Hindol",
    "Marga Bihag",
    "Maru Basant",
    "Maru Behag",
    "Maru Bihag",
    "Maru Dakhani",
    "Maru Kafi",
    "Maru Kalyan",
    "Maru Kauns",
    "Maru Khamaj",
    "Maru Sarang",
    "Maru",
    "Marwa Shree",
    "Marwa",
    "Mayuri",
    "Medhavi",
    "Meghbahar",
    "Meghranji",
    "Mehkali",
    "Mewara",
    "Mirabai ki Malhar",
    "Mishra Bhairavi",
    "Mishra Bihag",
    "Mishra Desh",
    "Mishra Gara",
    "Mishra Jhinjhoti",
    "Mishra Jog",
    "Mishra Kafi",
    "Mishra Kalyan",
    "Mishra Khamaj",
    "Mishra Kirwani",
    "Mishra Mand",
    "Mishra Manjha",
    "Mishra Narayani",
    "Mishra Nat",
    "Mishra Pahadi",
    "Mishra Pilu",
    "Mishra Shankara",
    "Mishra Shivaranjani",
    "Mishra Todi",
    "Mod Malhar",
    "Mohan Kauns",
    "Mohankauns",
    "Mohini",
    "Motaki",
    "MotakiTodi",
    "Mrig Savani",
    "Mudrik Kanada",
    "Mudrika Kanada",
    "Mudriki Kanada",
    "Mugdha Chandrika",
    "Muhammed",
    "Mukthipradayini",
    "Multani dhanashree",
    "Multani",
    "Mustang",
    "Nad",
    "Nada Kalyan",
    "Nadanamakriya",
    "Naga Gandhar",
    "Naga Pancham",
    "Nagadhwani Kanada",
    "Nagaswaravali",
    "Naiki Kanada",
    "Nanad",
    "Nanak Malhar",
    "Nand Basant",
    "Nand Kauns",
    "Nand Kedar",
    "Nand",
    "Nanda Dhwani",
    "Narayani",
    "Nat Bhairav",
    "Nat Bihag",
    "Nat Bilawal",
    "Nat Kamod",
    "Nat Kedar",
    "Nat Malhar",
    "Nat Nagari",
    "Nat",
    "Nat-Khamaj",
    "Natachandra",
    "Natacharuka",
    "Natahams",
    "Natakpriya",
    "Nathmira",
    "Natika",
    "Natnarayan",
    "NavRanjani",
    "Nayaki Kanada",
    "Neelambari",
    "Nepala Gauda",
    "Nepala",
    "Nindiyari",
    "Niranjani Todi",
    "Pahadi",
    "Palas Kafi",
    "Palas",
    "Palasi",
    "Pancha Jogeshwari",
    "Pancham Malkauns",
    "Pancham Se Gara",
    "Pancham se Gara",
    "Pancham Shadhav",
    "Pancham",
    "Paraj Basant",
    "Paraj Kalingada",
    "Paraj",
    "Paraji Bhairav",
    "Parameshwari",
    "Parbal",
    "Parbhati Bibhas",
    "Parbhati Dakhani",
    "Parbhati",
    "Pardesh",
    "Pat Bihag",
    "Pat Kafi",
    "Pat Ranjani",
    "Patdeep",
    "Patdeepak",
    "Patmanjari",
    "Phulashree",
    "Piloo Banjara",
    "Piloo Gara",
    "Piloo Ki Maanjh",
    "Piloo",
    "Pilu",
    "Pitambara",
    "Poorbya",
    "Prabhakali",
    "Prabhat Bhairav",
    "Prabhat",
    "Prabhateshwari",
    "Prabhati",
    "Pradeepaki",
    "Pratapvarali",
    "Priya Kalyan",
    "Punyaki",
    "Purabi Kalyan",
    "Purav Kalyan",
    "Puriya Dhanashree",
    "Puriya Kalyan",
    "Purna Chandrakauns",
    "Purva Kalyan",
    "Purva",
    "Purvi Bihag",
    "Purvi Kalyan",
    "Pushpa Chandrika",
    "Rageshree",
    "Rageshri Bahar",
    "Rageshri Kanada",
    "Rageshri Kauns",
    "Rageshri",
    "Rageswari",
    "Rahi",
    "Raisa Kanada",
    "Raj Bijoy",
    "Raj Kalyan",
    "Raja Kalyan",
    "Rajani Kalyan",
    "Rajeshri",
    "Rajya Kalyan",
    "Ram Gauri",
    "Ram Kalyan",
    "Rama",
    "Ramakiri",
    "Ramanandi Gauri",
    "Ramdasi Malhar",
    "Ramkali Dakhani",
    "Ramkali",
    "Ramkeli",
    "Ramsakh",
    "Rangeshwari",
    "Rasia Kanada",
    "Rasia",
    "Rasiya",
    "Rasranjani Rasavati",
    "Rati Bhairav",
    "Rati",
    "Rativallabha",
    "Rayasa Kanada",
    "Revagupta",
    "Rewa",
    "Rudhravati",
    "Rudra Pancham",
    "Rudra Ranjani",
    "Rupawati Kalyan",
    "Rupkali",
    "Rupmanjari Malhar",
    "Saanjhgiri",
    "Sagara",
    "Sagera",
    "Sagra",
    "Sagunaranjani",
    "Sahana Kanada",
    "Sahana",
    "Sahanki",
    "Saheli todi",
    "Saindhava",
    "Saindhavi",
    "Sajan",
    "Salagvarali",
    "Salang Sarang",
    "Salang",
    "Salu",
    "Samant Kalyan",
    "Samant Sarang",
    "Sampurna Bageshri",
    "Sampurna Bangala",
    "Sampurna Basakta",
    "Sampurna Bhairavi",
    "Sampurna Bibhas",
    "Sampurna Gauda",
    "Sampurna Hindol",
    "Sampurna Kedar",
    "Sampurna Malkauns",
    "Sampurna Ramkali",
    "Sampurna Sarang",
    "Sandhya Shree",
    "Sandhya",
    "Sangam Kedar",
    "Sanjani",
    "Sanjh Barari",
    "Sanjh Kalyan",
    "Sanjh Sarawali",
    "Sanjh Tarini",
    "Sanjh",
    "Santuri Todi",
    "Sar Nat",
    "Saradi",
    "Sarag",
    "Sarang Kauns",
    "Sarang",
    "Sarangi",
    "Sarasaangi",
    "Saraswati Chandra",
    "Saraswati Kalyan",
    "Saraswati Kedar",
    "Saraswati Sarang",
    "Saraswati",
    "Saravali",
    "Sarpada",
    "Sarparda Bilawal",
    "Sarparda",
    "Sathanka",
    "Saurati",
    "Savan Desaa",
    "Savan",
    "Savani Barwa",
    "Savani Bhatiyar",
    "Savani Bihag",
    "Savani Bilawal",
    "Savani Kalyan",
    "Savani Kedar",
    "Savani Nat",
    "Savani",
    "Saveri Todi",
    "Saveri",
    "Sazgiri",
    "Seehute",
    "Sehra",
    "Shadja Bhairav",
    "Shadja Hindol",
    "Shadjandhri",
    "Shahana Bahar",
    "Shahana Kanad",
    "Shahana Kanada",
    "Shahana",
    "Shailangi",
    "Shajda",
    "Shaktilak",
    "Shamvati",
    "Shankara Bihag",
    "Shankara Kalyan",
    "Shankara",
    "Sharada",
    "Shiv Abhogi",
    "Shiv Bhairav",
    "Shiv Kalyan",
    "Shiv Kauns",
    "Shiv Kedar",
    "Shiv Todi",
    "Shiv",
    "Shiva Kalyan",
    "Shiva Ranjani",
    "Shivaranjani",
    "Shivari",
    "Shivdhaam",
    "Shivmat Bhairav",
    "Shobhavari",
    "Shobhavati",
    "Shree Kalyan",
    "Shree",
    "Shreetanki",
    "Shubh Kalyan",
    "Shuddha Bahar",
    "Shuddha Barari",
    "Shuddha Basant",
    "Shuddha Bhairavi",
    "Shuddha Bihag",
    "Shuddha Bilawal",
    "Shuddha Desi",
    "Shuddha Dhanashree",
    "Shuddha Kafi",
    "Shuddha Kalyan",
    "Shuddha Kedar",
    "Shuddha Lalat",
    "Shuddha Malhar",
    "Shuddha Malu",
    "Shuddha Nat",
    "Shuddha Nishad Bageshri",
    "Shuddha Sarang",
    "Shuddha Sarangi",
    "Shuddha Shyam",
    "Shuddha Todi",
    "Shukla Bilawal",
    "Shukla",
    "Shyam Kalyan",
    "Shyam Kauns",
    "Shyam Kedar",
    "Shyam Sarang",
    "Shyam Shree",
    "Shyam",
    "Simhendramadhyam",
    "Sindh",
    "Sindhava",
    "Sindhavi Asavari",
    "Sindhimallari",
    "Sindhu Bahar",
    "Sindhu Bhairav",
    "Sindhu Bhairavi",
    "Sindhu",
    "Sindhura Bahar",
    "Sindhura Kafi",
    "Sindhura",
    "Sindhuri",
    "Siri Raag",
    "Sohani Bhatiyar",
    "Sohani Pancham",
    "Sohani",
    "Sohini",
    "Soma",
    "Sooha",
    "Sorat",
    "Sorath Desaa",
    "Sorath Malhar",
    "Sorath",
    "Sorathi",
    "Sorati",
    "Sourashtra Bhairav",
    "Sourashtra Gujjari",
    "Sourashtra",
    "Srirangapriya",
    "Subah Ki Malavi",
    "Subhabati",
    "Sugandh",
    "Sugandha",
    "Sugharai Kanada",
    "Sugharai",
    "Sughrai",
    "Suha Adana",
    "Suha Kanada",
    "Suha Malhar",
    "Suha Sugharai Kanada",
    "Suha Sughrai",
    "Suha Todi",
    "Suha",
    "Suhai",
    "Suhi Kafi",
    "Suhi lalit",
    "Suhi",
    "Sujani Malhar",
    "Sukhiya Bilawal",
    "Sukhiya",
    "Sukul Bilawal",
    "Sunand Bhairav",
    "Sunand Sarang",
    "Sundar Kali",
    "Sundar Kauns",
    "Sur Malhar",
    "Suranjani",
    "Surasati",
    "Surdasi Malhar",
    "Surmanand",
    "Surya Kauns",
    "Suryakant",
    "Suvarna",
    "Swanandi",
    "Swarparda",
    "Takkasaindhav",
    "Tanka",
    "Tanseni Madhuwanti",
    "Tappa Khamaj",
    "Telangi",
    "Telugu Kambhoji",
    "Thumari",
    "Thyagaraja Mangalam",
    "Tilak Bihag",
    "Tilak Des",
    "Tilak Kamod",
    "Tilak Kedar",
    "Tilak Malhar",
    "Tilak Shyam",
    "Tilang Bahar",
    "Tilang Kafi",
    "Tilang",
    "Timbanki",
    "Tirbhukti",
    "Tivrakallyan",
    "Todi Abheri",
    "Todi Ahiri",
    "Todi",
    "Todika",
    "Tribeni",
    "Triveni Gauri",
    "Triveni",
    "Tukhari",
    "Tulsikauns",
    "Turushka Gauda",
    "Turushka Todi",
    "Udan Chandrika",
    "Udan Kanta",
    "Udan",
    "Udasi Bhairav",
    "Udasi",
    "Uday Chandrika",
    "Uday Ravi",
    "Uday",
    "Uma Tilak",
    "Ushhaak",
    "Utara Kalyan",
    "Utari Basant",
    "Utari Gunakali",
    "Utari",
    "Uttari Gunkali",
    "Vachaspati",
    "Vachspati",
    "Vada Hamsa",
    "Vadhans Dakhani",
    "Vadhans",
    "Vanka",
    "Varati",
    "Vardhani",
    "Varorji",
    "Vasanta Mukhari",
    "Vasanta",
    "Vasanti",
    "Vaya",
    "Velaval",
    "Velavali",
    "Vibhas",
    "Vibhasaka",
    "Vibhavari",
    "Vidhyavati",
    "Vigiswari",
    "Vihang",
    "Vijayaranjani",
    "Vikram Bhairav",
    "Vilolika",
    "Vinod",
    "Virari",
    "Virat Bhairav",
    "Viyogvarali",
    "Vrindavani Sarang",
    "Vyjayanti",
    "Yaman Kalyan",
    "Yaman Manjh",
    "Yaman",
    "Yamani Basant",
    "Yamani Bilawal",
    "Yamani Hindol",
    "Yamani Kalyan",
    "Yamani",
    "Zeelaf",
    "Zilla Kafi",
    "Zilla",
    "Zim Kalyan"
]

artist_list = [
    "Sarod",
    "Sitar",
    "Violin",
    "Flute",
    "Surbahar",
    "Abhishek Borkar",
    "Abhishek Lahiri",
    "Ajoy Chakraborty",
    "Ali Ahmed Hussain Khan",
    "Ali Akbar Khan",
    "Allaudin Khan",
    "Amir Khan",
    "Amjad Ali Khan",
    "Annapurna Devi",
    "Apratim Majumdar",
    "Arnab Chakraborty",
    "Ashish Khan",
    "Bade Ghulam Ali Khan",
    "Bahadur Khan",
    "Basant Kabra",
    "Bhimsem Joshi",
    "Bismillah Khan",
    "Brij Narayan",
    "Buddhadev Dasgupta",
    "Budhaditya Mukherjee",
    "Debanjan Bhattacharjee",
    "Dhyanesh Khan",
    "Duet",
    "Enayet Khan",
    "Hafiz Ali Khan",
    "Hariprasad Chaurasia",
    "Imrat Khan",
    "Irfan Muhammad Khan",
    "Jagdish Prasad",
    "Jasraj",
    "Kamal Mallick",
    "Kaivalya Kumar Gurav",
    "Kala Ramnath",
    "Kaushiki Chakraborty",
    "Kedar Bodas",
    "Kishori Amonkar",
    "Krishna Bhatt",
    "Kumar Gandharva",
    "Kushal Das",
    "Mani Lal Nag",
    "N Rajam",
    "Nikhil Banerjee",
    "Nishat Khan",
    "Partho Sarothy",
    "Parveen Sultana",
    "Purbayan Chatterjee",
    "Pushparaj Kosthi",
    "Radhika Mohan Maitra",
    "Rais Khan",
    "Rajan Sajan Mishra",
    "Rajeev Taranath",
    "Rajrupa Chowdhury",
    "Ranadhir Roy",
    "Rashid Khan",
    "Ravi Shankar",
    "Salamat Nazakat Ali Khan",
    "Sanjoy Bandopadhyay",
    "Shahid Parvez",
    "Sharan Rani",
    "Shekhar Borkar",
    "Shivkumar Sharma",
    "Shubha Mudgal",
    "Shujaat Khan",
    "Sultan Khan",
    "Tarun Bhattacharya",
    "Tejendra Narayan Majumdar",
    "Uday Bhawalkar",
    "Ulhas Kushalkar",
    "Unknown",
    "V G Jog",
    "Vasant Rai",
    "Venkatesh Kumar",
    "Vilayat Khan",
    "Vishwa Mohan Bhatt",
    "Zareen Daruwala"
]


def searchYouTubeAndAddResults(raga_name, artist_name, oldIDList):
    max_r = 10
    flagUnknown = 0
    if artist_name == "Unknown":
        max_r = 3
        search_string = "rag "+raga_name
        flagUnknown = 1
    else:
        search_string = "rag "+raga_name+" "+artist_name
    results = []
    for tries in range(1, 11):
        try:
            results = YoutubeSearch(search_string, max_results=max_r).to_dict()
            break
        except requests.exceptions.RequestException as e:  # noqa: E501
            print("\n"+time.strftime("%d/%m/%Y %H:%M:%S\t")+str(e))
            if tries > 3:
                time.sleep(3)
    newResults = []
    for entry in results:
        if entry["id"] not in oldIDList:
            if flagUnknown == 1:
                searchedArtist = " "
            else:
                searchedArtist = artist_name
            if shouldAddEntry(raga_name, searchedArtist, entry):
                entry["searched_raga"] = raga_name
                if searchedArtist == " ":
                    entry["searched_artist"] = "Unknown"
                else:
                    entry["searched_artist"] = searchedArtist
                entry['url_suffix'] = "https://www.youtube.com"+entry['url_suffix']  # noqa: E501
                newResults.append(entry)
    return newResults


def shouldAddEntry(raga_name, artist_name, entry):
    # keyboard = Controller()
    raga_score = (fuzz.partial_ratio(raga_name, entry['title']))
    artist_score = (fuzz.partial_ratio(artist_name, entry['title']))
    # print("\nChecking \""+entry['title']+"\"\n\""+raga_name+"\" and \""+artist_name+"\"\nRaga Score: "+str(raga_score)+" Artist Score: "+str(artist_score))  # noqa: E501
    if raga_score >= 90 and artist_score >= 90:
        # print("Found Match")
        return True
    else:
        return False
        # Manually verify link by opening link in a tab in browser
        # webbrowser.open("https://www.youtube.com"+entry['url_suffix'])
        # time.sleep(1)
        # with keyboard.pressed(Key.alt_l):
        #     keyboard.tap(Key.tab)
        # time.sleep(1)
        # yes_choices = ['yes', 'y']
        # no_choices = ['no', 'n']
        # while True:
        #     user_input = input('Add link? yes(y)/no(n): ')
        #     # user_input = "y"
        #     if user_input.lower() in yes_choices:
        #         time.sleep(1)
        #         with keyboard.pressed(Key.alt_l):
        #             keyboard.tap(Key.tab)
        #         time.sleep(1)
        #         keyboard.tap(Key.space)
        #         with keyboard.pressed(Key.ctrl_l):
        #             keyboard.tap('w')
        #         return True
        #     elif user_input.lower() in no_choices:
        #         time.sleep(1)
        #         with keyboard.pressed(Key.alt_l):
        #             keyboard.tap(Key.tab)
        #         time.sleep(1)
        #         keyboard.tap(Key.space)
        #         with keyboard.pressed(Key.ctrl_l):
        #             keyboard.tap('w')
        #         return False
        #     else:
        #         continue


def main():
    with open('lastraga.txt', 'r') as file:
        lastRaga = file.read()
    flag = 0
    if len(lastRaga) == 0:
        flag = 1
    for raga in raga_list:
        if flag == 0:
            if raga == lastRaga:
                flag = 1
            continue
        with open('scrapeResults.json', 'r') as jsonfile:  # noqa: E501
            resultsHistory = json.load(jsonfile)
        oldIDList = []
        for oldEntry in resultsHistory:
            oldIDList.append(oldEntry["id"])
        for artist in artist_list:
            print("\n"+time.strftime("%d/%m/%Y %H:%M:%S")+"\tChecking Raga: "+str(raga)+", Artist: "+str(artist))  # noqa: E501
            tmpResult = (searchYouTubeAndAddResults(raga, artist, oldIDList))  # noqa: E501
            if len(tmpResult) > 0:
                for item in tmpResult:
                    resultsHistory.append(item)
            else:
                continue
        with open('scrapeResults.json', 'w') as jsonfile:  # noqa: E501
            json.dump(resultsHistory, jsonfile, indent=4, sort_keys=True)
        lastRaga = raga
        with open('lastraga.txt', 'w') as file:
            file.write(lastRaga)
    with open("scrapeResults.json", "r") as jsonfile:
        jsonData = json.load(jsonfile)
    # remove duplicate entries
    # new_list = []
    # oldIDList = set()
    # for item in jsonData:
    #     if item["id"] not in oldIDList:
    #         oldIDList.add(item["id"])
    #         new_list.append(item)
    #     else:
    #         print(item)
    # sortedJSON = sorted(new_list, key=lambda k: (k["searched_raga"], k["searched_artist"]))  # noqa: E501
    # with open('scrapeResults.json', 'w') as jsonfile:  # noqa: E501
    #     json.dump(sortedJSON, jsonfile, indent=4, sort_keys=True)
    sortedJSON = sorted(jsonData, key=lambda k: (k["searched_raga"], k["searched_artist"]))  # noqa: E501
    df = pd.json_normalize(sortedJSON)
    header = ["id", "searched_raga", "searched_artist", "title", "url_suffix", "duration"]  # noqa: E501
    df = pd.json_normalize(sortedJSON)
    df.to_csv("CSVData.csv", index=False, columns=header)


if __name__ == "__main__":
    main()
